### ISSUE TITLE
open cravat doesn't work anymore

### ISSUE THREAD

**Issue by jkobject** [KarchinLab/open-cravat#104]
I am trying to run open cravat and install base modules but it fails. steep to reproduce:
`sudo docker run -it karchinlab/opencravat bash`
then
`oc module install-base`

error:
```
Traceback (most recent call last):
  File "/usr/local/bin/oc", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/cravat/oc.py", line 220, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/cravat/cravat_admin.py", line 413, in install_base
    install_modules(args)
  File "/usr/local/lib/python3.6/site-packages/cravat/cravat_admin.py", line 260, in install_modules
    matching_names = au.search_remote(*args.modules)
  File "/usr/local/lib/python3.6/site-packages/cravat/admin_util.py", line 1495, in search_remote
    for module_name in list_remote():
  File "/usr/local/lib/python3.6/site-packages/cravat/admin_util.py", line 1250, in list_remote
    mic.update_remote(force=force)
  File "/usr/local/lib/python3.6/site-packages/cravat/admin_util.py", line 291, in update_remote
    self.remote.pop("hgvs", None)  # deprecate hgvs annotator
AttributeError: 'str' object has no attribute 'pop'
```

**Comment by jkobject** [comment]
no worries thanks!
