### ISSUE TITLE
Installation gives error `KeyError: 'wgcravat-converter'`

### ISSUE THREAD

**Issue by inodb** [KarchinLab/open-cravat#12]
```
$ cravat-admin install-base
Finished installation of excelreporter:1.0.2
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cravat/admin_util.py", line 610, in install_module
    install_module('wg' + module_name)
  File "/usr/local/lib/python3.7/site-packages/cravat/admin_util.py", line 534, in install_module
    version = get_remote_latest_version(module_name)
  File "/usr/local/lib/python3.7/site-packages/cravat/admin_util.py", line 394, in get_remote_latest_version
    return mic.remote[module_name]['latest_version']
KeyError: 'wgexcelreporter'
```

**Comment by rkiminsilico** [comment]
Thanks for the report. This error has been fixed and the fix will be included in the next release. Meanwhile, this error is a false alarm and can be safely ignored.

**Comment by inodb** [comment]
Sounds good - thanks @rkiminsilico !
