### ISSUE TITLE
"IndexError: list index out of range" exception in run_genemapper_mp

### ISSUE THREAD

**Issue by Zuulira** [KarchinLab/open-cravat#124]
Got this error when trying to use a .vcf file created using VarScan somatic following this tutorial (https://usegalaxy.eu/training-material/topics/variant-analysis/tutorials/somatic-variants/tutorial.html#variant-calling-and-classification) using galaxy build in reference genome hg38 (2013).

2022/09/20 22:02:44 cravat               C:\Program Files (x86)\open-cravat\python-3.7.2.amd64\Scripts\oc run C:\open-cravat\jobs\default\220920-220241\Galaxy35-[VarScan_somatic_on_data_34_and_data_32].vcf -a cancer_genome_interpreter cancer_hotspots cgc cgl civic civic_gene cosmic_gene cscape_coding dbcid mutpanning oncokb target -l hg38 --skip reporter --temp-files
2022/09/20 22:02:44 cravat               started: Tue Sep 20 22:02:44 2022
2022/09/20 22:02:44 cravat               input files: C:\open-cravat\jobs\default\220920-220241\Galaxy35-[VarScan_somatic_on_data_34_and_data_32].vcf
2022/09/20 22:02:44 cravat               input assembly: hg38
2022/09/20 22:02:44 cravat               version: open-cravat 2.2.7 C:\Program Files (x86)\open-cravat\python-3.7.2.amd64\lib\site-packages\cravat
2022/09/20 22:02:44 cravat               version: cancer_genome_interpreter 1.3.0 C:\open-cravat\modules\annotators\cancer_genome_interpreter
2022/09/20 22:02:44 cravat               version: cancer_hotspots 1.2.1 C:\open-cravat\modules\annotators\cancer_hotspots
2022/09/20 22:02:44 cravat               version: cgc 85.0.12 C:\open-cravat\modules\annotators\cgc
2022/09/20 22:02:44 cravat               version: cgl 1.1.0 C:\open-cravat\modules\annotators\cgl
2022/09/20 22:02:44 cravat               version: civic 1.0.16 C:\open-cravat\modules\annotators\civic
2022/09/20 22:02:44 cravat               version: civic_gene 1.0.10 C:\open-cravat\modules\annotators\civic_gene
2022/09/20 22:02:44 cravat               version: cosmic_gene 94.0.0 C:\open-cravat\modules\annotators\cosmic_gene
2022/09/20 22:02:44 cravat               version: cscape_coding 1.0.0 C:\open-cravat\modules\annotators\cscape_coding
2022/09/20 22:02:44 cravat               version: dbcid 1.0.1 C:\open-cravat\modules\annotators\dbcid
2022/09/20 22:02:44 cravat               version: mutpanning 1.0.0 C:\open-cravat\modules\annotators\mutpanning
2022/09/20 22:02:44 cravat               version: oncokb 1.1.3 C:\open-cravat\modules\annotators\oncokb
2022/09/20 22:02:44 cravat               version: target 3.1.0 C:\open-cravat\modules\annotators\target
2022/09/20 22:02:44 cravat               version: hg38 1.10.2 C:\open-cravat\modules\mappers\hg38
2022/09/20 22:02:44 cravat.converter     started: Tue Sep 20 22:02:44 2022
2022/09/20 22:02:44 cravat.converter     Input file(s): C:\open-cravat\jobs\default\220920-220241\Galaxy35-[VarScan_somatic_on_data_34_and_data_32].vcf
2022/09/20 22:02:46 cravat.converter     input format: vcf
2022/09/20 22:02:58 cravat.converter     error lines: 0
2022/09/20 22:02:58 cravat.converter     finished: Tue Sep 20 22:02:58 2022
2022/09/20 22:02:58 cravat.converter     num input lines: 115206
2022/09/20 22:02:58 cravat.converter     runtime: 12.814
2022/09/20 22:02:58 cravat               num_workers: 23
2022/09/20 22:02:58 cravat               input line chunksize=5008 total number of input lines=115206 number of chunks=23
2022/09/20 22:03:06 cravat               An unexpected exception occurred.
Traceback (most recent call last):
  File "C:\Program Files (x86)\open-cravat\python-3.7.2.amd64\lib\site-packages\cravat\cravat_class.py", line 539, in main
    self.run_genemapper_mp()
  File "C:\Program Files (x86)\open-cravat\python-3.7.2.amd64\lib\site-packages\cravat\cravat_class.py", line 1323, in run_genemapper_mp
    fn = fns[0]
IndexError: list index out of range
2022/09/20 22:03:06 cravat               finished with an exception: Tue Sep 20 22:03:06 2022
2022/09/20 22:03:06 cravat               runtime: 22.381s

**Comment by Zuulira** [comment]
somehow fixed it by renaming the vcf files
