### ISSUE TITLE
Python error while annotate the vcd file

### ISSUE THREAD

**Issue by SaraAlthubaiti** [KarchinLab/open-cravat#15]
Hi open-cravat team,

I'm facing an error while open cravat-web based, this is the error after I upload my vcf file:

2019/07/22 16:22:41 cravat               started: Mon Jul 22 16:22:41 2019
2019/07/22 16:22:41 cravat               input assembly: hg38
2019/07/22 16:22:41 cravat.converter     started: Mon Jul 22 16:22:41 2019
2019/07/22 16:22:41 cravat.converter     input files: /Users/Shared/open-cravat/jobs/default/190722-162237/CosmicCodingMuts.vcf
2019/07/22 16:22:55 cravat.converter     input format: vcf
2019/07/22 16:24:36 cravat.converter     error lines: 0
2019/07/22 16:24:36 cravat.converter     finished: Mon Jul 22 16:24:36 2019
2019/07/22 16:24:36 cravat.converter     num input lines: 4668387
2019/07/22 16:24:36 cravat.converter     runtime: 100.444
2019/07/22 16:24:36 cravat.mapper        input file: /Users/Shared/open-cravat/jobs/default/190722-162237/CosmicCodingMuts.vcf.crv
2019/07/22 16:24:44 cravat.mapper        mapper database: /Users/Shared/open-cravat/modules/mappers/hg38/data/hg38.sqlite
2019/07/22 16:24:44 cravat.mapper        started: Mon Jul 22 16:24:44 2019
2019/07/22 16:25:50 cravat.mapper        Traceback (most recent call last):
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/base_mapper.py", line 168, in run
    crx_data, alt_transcripts = self.map(crv_data)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 80, in map
    all_hits += self._get_coding_hits(crv_data)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 218, in _get_coding_hits
    self._fill_coding_so(hit)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 308, in _fill_coding_so
    self._fill_snv_pchange(hit)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 333, in _fill_snv_pchange
    hit.aalt = cravat.translate_codon(hit.full_alt)
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/util.py", line 111, in translate_codon
    return codon_table[bases]
KeyError: 'CNC'
2019/07/22 16:25:50 cravat               An unexpected exception occurred.
Traceback (most recent call last):
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/cravat_class.py", line 313, in main
    self.run_genemapper()
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/cravat_class.py", line 569, in run_genemapper
    genemapper.run()
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/base_mapper.py", line 173, in run
    self._log_runtime_error(ln, line, e)
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/base_mapper.py", line 252, in _log_runtime_error
    raise e
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/base_mapper.py", line 168, in run
    crx_data, alt_transcripts = self.map(crv_data)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 80, in map
    all_hits += self._get_coding_hits(crv_data)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 218, in _get_coding_hits
    self._fill_coding_so(hit)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 308, in _fill_coding_so
    self._fill_snv_pchange(hit)
  File "/Users/Shared/open-cravat/modules/mappers/hg38/hg38.py", line 333, in _fill_snv_pchange
    hit.aalt = cravat.translate_codon(hit.full_alt)
  File "/Applications/OpenCRAVAT.app/Contents/Resources/lib/python3.7/site-packages/cravat/util.py", line 111, in translate_codon
    return codon_table[bases]
KeyError: 'CNC'
2019/07/22 16:25:50 cravat               finished with an exception: Mon Jul 22 16:25:50 2019
2019/07/22 16:25:50 cravat               runtime: 188.819s
2019/07/22 16:26:32 cravat               started: Mon Jul 22 16:26:32 2019
2019/07/22 16:26:32 cravat               input assembly: hg38
2019/07/22 16:26:32 cravat               finished: Mon Jul 22 16:26:32 2019
2019/07/22 16:26:32 cravat               runtime: 0.032s

**Comment by kmoad** [comment]
Hi Sara, thanks for the bug. The issue here is that the vcf has `N` as an alternate base for this variant. Currently, open-cravat doesn't handle ambiguous alternate bases. The behavior here should have been for open-cravat to skip that line and continue with the rest of the input. We've fixed the hg38 gene mapper to do this. If you restart your web server there should be a prompt and button in the top right that will get the new version. Please let me know if this works.

**Comment by SaraAlthubaiti** [comment]
Thanks a lot, I follow what you said and now it's working.
