### ISSUE TITLE
gather_machine_data function fails on WSL

### ISSUE THREAD

**Issue by BnetButter** [KarchinLab/open-cravat#175]
in `/cravat/cravat_metrics.py`, line 38:

`self.machinedata['fileSystem'] = psutil.disk_partitions()[0].fstype`

This line throws an index error. I think it's because I'm on WSL. Fixed by replacing the line with:

`self.machinedata['fileSystem'] = lxfs`

Full stack trace
```
Traceback (most recent call last):
  File "/home/bnetbutter/Documents/open-cravat/cravat/cravat_class.py", line 336, in __init__
    self.metricObj = metrics.cravatMetrics()
  File "/home/bnetbutter/Documents/open-cravat/cravat/cravat_metrics.py", line 27, in __init__
    self.gather_machine_data()
  File "/home/bnetbutter/Documents/open-cravat/cravat/cravat_metrics.py", line 38, in gather_machine_data
    self.machinedata['fileSystem'] = psutil.disk_partitions()[0].fstype
IndexError: list index out of range
```

**Comment by kmoad** [comment]
Fixed in dev
