### ISSUE TITLE
Empty Results...

### ISSUE THREAD

**Issue by CypherAce** [KarchinLab/open-cravat#19]
I'm having an issue where I get empty results when I try to do a fairly standard annotation run. Here's the command I've used:

`cravat my_data.vcf -l hg38 -t tsv`

Here's the output:
```

Input file(s): my_data.vcf
Genome assembly: hg38
Running converter...
	Converter (converter)         	finished in 2.788s
Running gene mapper...
	UCSC hg38 Gene Mapper (hg38)  	finished in 0.038s
Running annotators...
        revel: started at Wed Jan 22 08:03:15 2020
        revel: finished at Wed Jan 22 08:03:15 2020
        revel: runtime 0.001s
        hgvs: started at Wed Jan 22 08:03:15 2020
        hgvs: finished at Wed Jan 22 08:03:15 2020
        hgvs: runtime 0.002s
        clinvar: started at Wed Jan 22 08:03:15 2020
        sift: started at Wed Jan 22 08:03:15 2020
        phylop: started at Wed Jan 22 08:03:15 2020
        clinvar: finished at Wed Jan 22 08:03:15 2020
        clinvar: runtime 0.002s
        sift: finished at Wed Jan 22 08:03:15 2020
        sift: runtime 0.001s
        gnomad: started at Wed Jan 22 08:03:15 2020
        phylop: finished at Wed Jan 22 08:03:15 2020
        phylop: runtime 0.002s
        vest: started at Wed Jan 22 08:03:15 2020
        gnomad: finished at Wed Jan 22 08:03:15 2020
        gnomad: runtime 0.002s
        vest: finished at Wed Jan 22 08:03:15 2020
        vest: runtime 0.009s
        polyphen2: started at Wed Jan 22 08:03:15 2020
        polyphen2: finished at Wed Jan 22 08:03:15 2020
        polyphen2: runtime 0.001s
	annotator(s) finished in 1.147s
Running aggregator...
	Variants                      	finished in 1.054s
	Genes                         	finished in 0.923s
	Samples                       	finished in 1.094s
	Tags                          	finished in 2.050s
Running postaggregators...
	VCF Info (vcfinfo)            	finished in 0.430s
	Tag Sampler (tagsampler)      	finished in 0.573s
Running reporter...
	TSV Reporter (tsvreporter)    	
            hg38: started getting gene summary data
            hg38: finished getting gene summary data in 0.000s
            vest: getting gene summary data
            vest: finished getting gene summary data in 0.000s
	    finished in 0.296s
Finished normally. Runtime: 10.741s
```
Here's an example row of the data (I've changed/spoofed some of the values):

chr3 | 7966478 | . | A | G | 44 | PASS | P=0.999544 | GT:RV:VV:ZQ:GQ:PL | 1/1:30:0:20:.:1228,217,0

**Comment by kmoad** [comment]
To help me replicate this, could you send the output of `cva version` and `cva ls`. That will tell me which version of open-cravat and the modules you're using.

**Comment by CypherAce** [comment]
Sure thing, if it helps I know this data was annotated by your software before I'm just doing it again on a different installation with more annotations.
```
cva version
1.6.1
```
```
cva ls
Name                          Title                               Type               Version       Data source ver      Size        
clinvar                       ClinVar                             annotator          2019.08.23    2019.01.02           89.7 MB     
cravat-converter              Cravat Converter                    converter          1.0.5                              12.0 kB     
csvreporter                   CSV Reporter                        reporter           1.0.7                              12.8 kB     
excelreporter                 Excel Reporter                      reporter           1.0.5                              1.1 MB      
gnomad                        gnomAD                              annotator          2.1.8         v2.1                 17.4 GB     
hg38                          UCSC hg38 Gene Mapper               mapper             1.2.7                              7.2 GB      
hgvs                          HGVS Format                         annotator          1.0.7         v15.11               205.8 MB    
oldcravat-converter           OldCravat Converter                 converter          1.0.2                              12.4 kB     
phylop                        PhyloP                              annotator          3.5.8         dbNSFP v4.0b1        14.2 GB     
polyphen2                     PolyPhen-2                          annotator          1.0.0         2                    6.1 GB      
revel                         REVEL                               annotator          2019.05.13    2017-06-21           3.0 GB      
sift                          SIFT                                annotator          1.0.0         SIFT4G 2016-02-22    14.8 GB     
tagsampler                    Tag Sampler                         postaggregator     1.1.1                              4.8 kB      
textreporter                  Text Reporter                       reporter           1.0.5                              8.5 kB      
tsvreporter                   TSV Reporter                        reporter           1.0.7                              15.4 kB     
vcf-converter                 VCF Converter                       converter          1.1.6                              38.1 kB     
vcfinfo                       VCF Info                            postaggregator     1.1.4                              12.2 kB     
vest                          VEST4                               annotator          4.1.2         v4                   9.7 GB      
wgbase                        Base information                    webviewerwidget    1.0.8                              3.4 kB      
wgcircossummary               Circos Summary                      webviewerwidget    1.1.8                              620.0 kB    
wgcodingvsnoncodingsummary    Coding vs Noncoding Summary         webviewerwidget    1.0.6                              3.1 kB      
wggosummary                   Gene Ontology Summary               webviewerwidget    1.0.8                              10.6 MB     
wglollipop                    Protein diagram                     webviewerwidget    1.1.10                             73.2 MB     
wgnote                        Note                                webviewerwidget    1.0.4                              4.4 kB      
wgsosamplesummary             Sequence Ontology Sample Summary    webviewerwidget    1.2.3                              13.1 kB     
wgsosu
```mmary                   Sequence Ontology Summary           webviewerwidget    1.1.3                              3.8 kB

**Comment by rkiminsilico** [comment]
Do you see any exception message in my_data.vcf.log and my_data.vcf.err?

**Comment by CypherAce** [comment]
Yes, there's actually an error for every line/variant of the input.
They're all like this (data slightly changed for privacy reasons):
```
SOURCE:error.converter      
LINE:1
INPUT:chr1	7953488	.	A	G	33	PASS	P=0.999544	GT:VR:RR:DP:GQ:PL	1/1:40:0:40:.:1118,117,0
ERROR:list index out of range
```

**Comment by rkiminsilico** [comment]
Thanks. my_data.vcf.log should have an exception message with a stacktrace. Can you post here?

**Comment by CypherAce** [comment]
Here's the log:
```
2020/01/22 08:03:12 cravat               started: Wed Jan 22 08:03:12 2020
2020/01/22 08:03:12 cravat               conf file: None
2020/01/22 08:03:12 cravat               input files: [redacted]
2020/01/22 08:03:12 cravat               input assembly: hg38
2020/01/22 08:03:12 cravat.converter     started: Wed Jan 22 08:03:12 2020
2020/01/22 08:03:12 cravat.converter     input files: [redacted]
2020/01/22 08:03:12 cravat.converter     input format: vcf
2020/01/22 08:03:12 cravat.converter     Traceback (most recent call last):
  File "[redacted]/lib/python3.7/site-packages/cravat/cravat_convert.py", line 310, in run
    all_wdicts = self.primary_converter.convert_line(l)
  File "[redacted]/lib/python3.7/site-packages/cravat/modules/converters/vcf-converter/vcf-converter.py", line 116, in convert_line
    sample = self.samples[sample_no]
IndexError: list index out of range
2020/01/22 08:03:15 cravat.converter     error lines: 39713
2020/01/22 08:03:15 cravat.converter     finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.converter     num input lines: 39713
2020/01/22 08:03:15 cravat.converter     runtime: 2.538
2020/01/22 08:03:15 cravat.mapper        input file: [redacted]
2020/01/22 08:03:15 cravat.mapper        mapper database: [redacted]/lib/python3.7/site-packages/cravat/modules/mappers/hg38/data/hg38.sqlite
2020/01/22 08:03:15 cravat.mapper        started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.mapper        finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.mapper        runtime:  0.000
2020/01/22 08:03:15 cravat               num_workers: 7
2020/01/22 08:03:15 cravat.revel         started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.revel         finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.revel         runtime: 0.001s
2020/01/22 08:03:15 cravat.hgvs          started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.hgvs          finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.hgvs          runtime: 0.002s
2020/01/22 08:03:15 cravat.clinvar       started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.sift          started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.phylop        started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.clinvar       finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.clinvar       runtime: 0.002s
2020/01/22 08:03:15 cravat.sift          finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.sift          runtime: 0.001s
2020/01/22 08:03:15 cravat.gnomad        started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.phylop        finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.phylop        runtime: 0.002s
2020/01/22 08:03:15 cravat.vest          started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.gnomad        finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.gnomad        runtime: 0.002s
2020/01/22 08:03:15 cravat.vest          finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.vest          runtime: 0.009s
2020/01/22 08:03:15 cravat.polyphen2     started: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.polyphen2     finished: Wed Jan 22 08:03:15 2020
2020/01/22 08:03:15 cravat.polyphen2     runtime: 0.001s
2020/01/22 08:03:16 cravat.aggregator    level: variant
2020/01/22 08:03:16 cravat.aggregator    input directory: [redacted]
2020/01/22 08:03:17 cravat.aggregator    started: Wed Jan 22 08:03:17 2020
2020/01/22 08:03:17 cravat.aggregator    finished: Wed Jan 22 08:03:17 2020
2020/01/22 08:03:17 cravat.aggregator    runtime: 0.185
2020/01/22 08:03:17 cravat.aggregator    level: gene
2020/01/22 08:03:17 cravat.aggregator    input directory: [redacted]
2020/01/22 08:03:18 cravat.aggregator    started: Wed Jan 22 08:03:18 2020
2020/01/22 08:03:18 cravat.aggregator    finished: Wed Jan 22 08:03:18 2020
2020/01/22 08:03:18 cravat.aggregator    runtime: 0.003
2020/01/22 08:03:18 cravat.aggregator    level: sample
2020/01/22 08:03:18 cravat.aggregator    input directory: [redacted]
2020/01/22 08:03:19 cravat.aggregator    started: Wed Jan 22 08:03:19 2020
2020/01/22 08:03:19 cravat.aggregator    finished: Wed Jan 22 08:03:19 2020
2020/01/22 08:03:19 cravat.aggregator    runtime: 0.003
2020/01/22 08:03:19 cravat.aggregator    level: mapping
2020/01/22 08:03:19 cravat.aggregator    input directory: [redacted]
2020/01/22 08:03:20 cravat.aggregator    started: Wed Jan 22 08:03:20 2020
2020/01/22 08:03:20 cravat.aggregator    finished: Wed Jan 22 08:03:20 2020
2020/01/22 08:03:20 cravat.aggregator    runtime: 0.003
2020/01/22 08:03:21 cravat.vcfinfo       started: Wed Jan 22 08:03:21 2020
2020/01/22 08:03:22 cravat.vcfinfo       finished: Wed Jan 22 08:03:22 2020
2020/01/22 08:03:22 cravat.vcfinfo       runtime: 0.429
2020/01/22 08:03:22 cravat.tagsampler    started: Wed Jan 22 08:03:22 2020
2020/01/22 08:03:22 cravat.tagsampler    finished: Wed Jan 22 08:03:22 2020
2020/01/22 08:03:22 cravat.tagsampler    runtime: 0.572
2020/01/22 08:03:22 cravat.tsvreporter   started: Wed Jan 22 08:03:22 2020
2020/01/22 08:03:23 cravat.mapper        input file: [redacted]/__dummy__
2020/01/22 08:03:23 cravat.tsvreporter   finished: Wed Jan 22 08:03:23 2020
2020/01/22 08:03:23 cravat.tsvreporter   runtime: 0.295
2020/01/22 08:03:23 cravat               finished: Wed Jan 22 08:03:23 2020
2020/01/22 08:03:23 cravat               runtime: 10.741s
```

**Comment by rkiminsilico** [comment]
Thanks. The exception means that the samples defined in the header of the vcf format input file has fewer samples than those in the data rows. For example, if a vcf input file is:
```
#CHROM POS     ID        REF    ALT     QUAL FILTER INFO                              FORMAT      NA00001
20     14370   rs6054257 G      A       29   PASS   NS=3;DP=14;AF=0.5;DB;H2           GT:GQ:DP:HQ 0|0:48:1:51,51 1|0:48:8:51,51 1/1:43:5:.,.
```
The header has 1 sample and the data row has 3 samples. The same exception can happen if the data row has 1 sample and the header does not have any sample column. Is this the case by any chance?

**Comment by CypherAce** [comment]
These files were subsetted from larger vcfs using tabix based on bed files so they lack an actual VCF header or a header of any sort.

**Comment by rkiminsilico** [comment]
I see. vcf-converter module should be changed to handle this case, as vcf-converter module currently expects full compliance to VCF Format 4.2. I think that something can be done about this. We are close to releasing the next version of OpenCRAVAT (v1.7.0). We'll also update vcf-converter and let you know here. Meanwhile, a possible workaround is using a header line with dummy sample IDs. For example, if your input file has only one sample data (as in your example input), add the following line at the top of the file:
```
##fileformat=VCFv4.2
```
and add the following line (tab-separated) just before the beginning of the data lines:
```
#CHROM POS      ID        REF    ALT     QUAL FILTER INFO                              FORMAT      sample1
```
Thus, if your original input file was
```
chr1	7953488	.	A	G	33	PASS	P=0.999544	GT:VR:RR:DP:GQ:PL	1/1:40:0:40:.:1118,117,0
```
It will become (tab-separated)
```
##fileformat=VCFv4.2
#CHROM POS      ID        REF    ALT     QUAL FILTER INFO                              FORMAT      sample1
chr1	7953488	.	A	G	33	PASS	P=0.999544	GT:VR:RR:DP:GQ:PL	1/1:40:0:40:.:1118,117,0
```

**Comment by rkiminsilico** [comment]
@CypherAce Have you tried adding the two header lines as I described above?
