### ISSUE TITLE
sqlite3.OperationalError: no such column: tagsampler__numsample

### ISSUE THREAD

**Issue by joshua-gould** [KarchinLab/open-cravat#25]
```
conda create --name cravat
conda activate cravat
conda install pip
pip install open-cravat
oc module install --yes clinvar vcfreporter vcf-converter hg38
wget https://raw.githubusercontent.com/vcflib/vcflib/master/samples/sample.vcf
oc run sample.vcf --repeat converter -t vcf -l hg38
```

Running reporter...
	VCF Reporter (vcfreporter)    	Traceback (most recent call last):
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/cravat/cravat_class.py", line 875, in run_reporter
    await reporter.run()
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/cravat/cravat_report.py", line 354, in run
    await self.run_level(level)
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/cravat/cravat_report.py", line 219, in run_level
    gene_summary_data = await o.get_gene_summary_data(self.cf)
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/cravat/base_mapper.py", line 288, in get_gene_summary_data
    rows = await cf.get_variant_data_for_cols(cols)
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/cravat/cravat_filter.py", line 676, in get_variant_data_for_cols
    await self.cursor.execute(q)
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/aiosqlite3/cursor.py", line 130, in execute
    res = yield from self._execute(self._cursor.execute, sql, parameters)
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/aiosqlite3/cursor.py", line 56, in _execute
    res = yield from self._conn.async_execute(func, *args, **kwargs)
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/aiosqlite3/connection.py", line 137, in async_execute
    return (yield from self._execute(func, *args, **kwargs))
  File "/opt/anaconda3/envs/cravat/lib/python3.7/site-packages/aiosqlite3/connection.py", line 128, in _execute
    func
  File "/opt/anaconda3/envs/cravat/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
sqlite3.OperationalError: no such column: tagsampler__numsample

**Comment by rkiminsilico** [comment]
Did you run `oc module install-base` (described in https://github.com/KarchinLab/open-cravat/wiki/1.-Installation-Instructions)?

**Comment by joshua-gould** [comment]
Sorry, I didn't realize that was required. This fixes the issue. Thanks.
